//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frota_de_Veículos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrotadeVeículoEntities1 : DbContext
    {
        public FrotadeVeículoEntities1()
            : base("name=FrotadeVeículoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Motorista> Motoristas { get; set; }
        public virtual DbSet<OrdemServico> OrdemServicoes { get; set; }
        public virtual DbSet<Posto> Postoes { get; set; }
        public virtual DbSet<TipoCombustivel> TipoCombustivels { get; set; }
        public virtual DbSet<TipoCombustível> TipoCombustível { get; set; }
        public virtual DbSet<Veiculo> Veiculoes { get; set; }
    }
}
