//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frota_de_Veículos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServico()
        {
            this.Postoes = new HashSet<Posto>();
        }
    
        public int OrdSerId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<double> QuantidadeCombustivel { get; set; }
        public int MotId { get; set; }
        public int CombId { get; set; }
    
        public virtual Motorista Motorista { get; set; }
        public virtual TipoCombustivel TipoCombustivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posto> Postoes { get; set; }
    }
}
