//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frota_de_Veículos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posto
    {
        public int PoId { get; set; }
        public string Nome { get; set; }
        public string Localizacao { get; set; }
        public int OrdSerId { get; set; }
    
        public virtual OrdemServico OrdemServico { get; set; }
    }
}
