//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frota_de_Veículos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCombustível
    {
        public int CombId { get; set; }
        public Nullable<double> ValorLitro { get; set; }
        public string Nome { get; set; }
    }
}
